################################################################################
# JaCaMo-REST: Integration Demo (Node-RED + MQTT)
################################################################################
# docker-compose -f docker-compose.yml -p demo up
################################################################################
version: "3.7"

services:
  nodered:
    image: nodered/node-red:latest
    hostname: nodered
    environment:
      - TZ=America/Sao_Paulo
      - FLOWS=flows/flows.json
    ports:
      - "1880:1880"
    networks:
      - jacamo-nodered-net
    volumes:
      - "./node-red:/data"

  alice:
    image: otaviomatoso/jacamo_rest_demo_nodered:0.1
    hostname: alice
    environment:
      - TZ=America/Sao_Paulo
    ports:
      - "8080:8080"
      - "3272:3272"
      - "3273:3273"
    networks:
      - jacamo-nodered-net
    depends_on:
      - nodered
    volumes:
      - "./jacamo/src-alice:/app/src"

  bob:
    image: otaviomatoso/jacamo_rest_demo_nodered:0.1
    hostname: bob
    environment:
      - TZ=America/Sao_Paulo
    ports:
      - "8081:8081"
      - "3275:3272"
      - "3276:3273"
    networks:
      - jacamo-nodered-net
    depends_on:
      - nodered
    volumes:
      - "./jacamo/src-bob:/app/src"

networks:
  jacamo-nodered-net:
